# Use postgres/postgres user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
        - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  # mongo:
  #   image: mongo
  #   restart: unless-stopped
  #   # ports:
  #   #   - 27017:27017
  #   environment:
  #     # - MONGO_INITDB_DATABASE=test
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root

  # mongo-express:
  #   image: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=root